name: Auto Update

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  auto-update:
    name: Auto Update
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup jq
        uses: dcarbone/install-jq-action@v3
      - name: Update APM libs
        working-directory: apm
        run: |
          ./update.sh
      - name: Update Serverless libs
        working-directory: serverless
        run: |
          ./update.sh
      - name: Commit & Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add apm/*
          git add serverless/*
          git commit -am "chore: auto update lib versions" || echo "We're good for now. See you next time!"
          git pull --rebase
          git push